---
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: false

  vars:
    INSTALL_DIR: "/sas/install"
    NFS_SHARE_DIR: "{{ INSTALL_DIR }}/nfs"
    ANSIBLE_KEY_DIR: "{{ NFS_SHARE_DIR }}/ansible_key"
    READINESS_FLAGS_DIR: "{{ NFS_SHARE_DIR }}/readiness_flags"
    LOGS_DIR: "/var/log/sas/install"

  tasks:
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0777
        owner: "{{ INSTALL_USER }}"
        group: "{{ INSTALL_USER }}"
      with_items:
        - "{{ INSTALL_DIR }}"
        - "{{ NFS_SHARE_DIR }}"
        - "{{ ANSIBLE_KEY_DIR }}"
        - "{{ READINESS_FLAGS_DIR }}"
        - "{{ LOGS_DIR }}"

    #
    #  NFS setup
    #
    - name: nfs setup - create /etc/exports
      shell:
        cmd: echo -n "{{ NFS_SHARE_DIR }} *(rw,sync)" > /etc/exports
    - name: nfs setup - install nfs
      yum:
        name:
          - nfs-utils
          - nfs-utils-lib
        state: installed
    - name: nfs setup - start nfs
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - rpcbind
        - nfs

    #
    #  Ansible Key
    #
    - name: Create Ansible key
      become: yes
      become_user: "{{ INSTALL_USER }}"
      shell:
        cmd: "ssh-keygen -t rsa -f /home/{{ INSTALL_USER }}/.ssh/id_rsa -q -N ''"
      args:
         creates: "/home/{{ INSTALL_USER }}/.ssh/id_rsa"

    - name: Distribute Ansible key
      become: yes
      become_user: "{{ INSTALL_USER }}"
      shell:
        cmd: "cp /home/{{ INSTALL_USER }}/.ssh/id_rsa.pub {{ ANSIBLE_KEY_DIR }}/id_rsa.pub"
      args:
         creates: "{{ ANSIBLE_KEY_DIR }}/id_rsa.pub"



