---
- hosts: localhost
  become: yes
  become_user: root


  tasks:

    - name: wait for all volume attachments to be complete
      shell: |
        echo "Checking volume attachments" >> "$CMDLOG"
        STATUS="status"
        until [ $(echo "$STATUS" | wc -w) = $(echo "$STATUS" | sed 's/CREATE_COMPLETE/CREATE_COMPLETE\n/g' | grep -c "CREATE_COMPLETE") ]; do
          sleep 1
          STATUS=$(aws --no-paginate --region "{{AWSRegion}}" cloudformation describe-stack-resources --stack-name "{{CloudFormationStack}}"  --query 'StackResources[?ResourceType ==`AWS::EC2::VolumeAttachment`].ResourceStatus' --output text)
          [ "$STATUS" = "" ] && STATUS="status"
          if [ "$(echo "$STATUS" | grep "CREATE_FAILED")" ]; then exit 1; fi
          check_stack_status
        done