---
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    - name: wait for VMs to be be ready
      wait_for:
        path: "{{ READINESS_FLAGS_DIR }}/{{ item }}"
        state: present
        timeout: 300
        sleep: 1
      # TODO: replace items with variable
      with_items:
        - services
        - controller

    - name: create /etc/hosts lines for viya hosts
      lineinfile:
        path: /tmp/hostnames.txt
        create: yes
        state: present
        line: "{{ lookup('file', '{{READINESS_FLAGS_DIR}}/{{item}}') }} {{item}}.viya.sas {{item}}"
      # TODO: replace items with variable
      with_items:
        - services
        - controller
      tags:
        - hostnames

    - name: create /etc/hosts line for ansible controller
      lineinfile:
        path: /tmp/hostnames.txt
        state: present
        line: "{{ ansible_eth0.ipv4.address }} ansible.viya.sas ansible"
      tags:
        - hostnames

