---


- name: Download sas-orchestration cli
  hosts: [AnsibleController]
  gather_facts: true
  roles:
    - role: prepare_deployment/download_orchestration_cli
  tags:
    - download_orchestration_cli

- name: Provide mirror access
  hosts: [MirrorServer]
  become: yes
  become_user: root
  roles:
    - role: prepare_deployment/deployment_mirror
      when: DEPLOYMENT_MIRROR | default()
  tags:
    - deployment_mirror

