---
- hosts: localhost
  become: yes
  become_user: root
  gather_facts: true

  tasks:

    - name: wait for VMs to be be ready
      wait_for:
        path: "{{ READINESS_FLAGS_DIR }}/{{ item }}"
        state: present
        timeout: 300
        sleep: 1
      with_items: "{{ groups['sas-servers'] }}"

