---

- name: set sas/access variants
  set_fact:
     sas_ld_library_path: $LD_LIBRARY_PATH:$ODBCHOME/lib:/opt/sas/spre/home/lib64
     cas_ld_library_path: $LD_LIBRARY_PATH:$ODBCHOME/lib:$JAVA_HOME/lib/amd64/server:/opt/sas/viya/home/lib64
  when: HAS_ODBC | default("0") == "0"


- name: set sas/access variants for ODBC
  set_fact:
     sas_ld_library_path: "$LD_LIBRARY_PATH:$ODBCHOME/lib:/opt/sas/spre/home/lib64:/usr/pgsql-11/lib:{{ UNIXODBC_LOCATION }}/lib"
     cas_ld_library_path: "$LD_LIBRARY_PATH:$ODBCHOME/lib:$JAVA_HOME/lib/amd64/server:/opt/sas/viya/home/lib64:/usr/pgsql-11/lib:{{ UNIXODBC_LOCATION }}/lib"
  when: HAS_ODBC | default("0") == "1"


- name: set sas/access variants for ODBC to Redshift
  set_fact:
     sas_ld_library_path: "{{sas_ld_library_path}}:/opt/amazon/redshiftodbc/lib/64"
     cas_ld_library_path: "{{cas_ld_library_path}}:/opt/amazon/redshiftodbc/lib/64"
  ## when SAS/Access to Redshift is licensed we do not want to configure the ODBC to Redshift
  #when: HAS_ODBC | default("0") == "1" and HAS_REDSHIFT | default("0") == "0"
  when: HAS_ODBC | default("0") == "1" 


- name: change cas cache location
  lineinfile:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp: "CAS_DISK_CACHE:"
    line: "     CAS_DISK_CACHE: {{ CASCACHE_DIR }}"
    backup: yes


- name: change saswork location
  blockinfile:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    insertafter: EOF
    marker: "# {mark} add saswork location"
    block: |
      SASV9_CONFIGURATION:
        1: '/* this will send the SASWORK to the /sastmp location */'
        2: 'WORK {{ SASWORK_DIR }}'

- name: set SASStudio folder root (remove if it exists)
  lineinfile:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp: "webdms.showSystemRoot:"
    state: absent

- name: set SASStudio folder root
  replace:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp:  'STUDIO_CONFIGURATION:\n  init:'
    replace: 'STUDIO_CONFIGURATION:\n  init:\n    webdms.showSystemRoot: false'

- name: set workspaceserver settings
  replace:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp: '#FOUNDATION_CONFIGURATION:'
    replace: 'FOUNDATION_CONFIGURATION:'

- name: set sas/access environment vars for workspaceserver
  blockinfile:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    marker: '#{mark} configure sas/access environment variables (workspaceserver)'
    insertafter: '^FOUNDATION_CONFIGURATION:'
    block: |2
          1: ODBCHOME={{ SAS_INSTALL_DIR }}/spre/home/lib64/accessclients
          2: ODBCINI=$ODBCHOME/odbc.ini
          3: ODBCINST=$ODBCHOME/odbcinst.ini
          4: ODBCSYSINI=$ODBCHOME
          5: LD_LIBRARY_PATH={{ sas_ld_library_path }}
          6: PATH=$PATH:/opt/sas/spre/home/lib64/psql
          7: PGCLIENTENCODING=UTF-8
          8: EASYSOFT_UNICODE=yes

- name: set CAS Settings
  replace:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp:  '#CAS_SETTINGS:'
    replace: 'CAS_SETTINGS:'


- name: set sas/access environment vars for cas controller
  blockinfile:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    marker: '#{mark} configure sas/access environment variables (cas)'
    insertafter: '^CAS_SETTINGS:'
    block: |2
          1: ODBCHOME={{ SAS_INSTALL_DIR }}/viya/home/lib64/accessclients
          2: ODBCINI=$ODBCHOME/odbc.ini
          3: ODBCINST=$ODBCHOME/odbcinst.ini
          4: ODBCSYSINI=$ODBCHOME
          5: PGCLIENTENCODING=UTF-8
          6: JAVA_HOME=/usr/lib/jvm/jre
          7: LD_LIBRARY_PATH={{ cas_ld_library_path }}
          8: EASYSOFT_UNICODE=yes

- name: set pg host
  replace:
    dest: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
    regexp:  '\ \ deployTarget'
    replace: '  {{ groups["PostgresPrimaryServer"]|first }}'

-  name: remove numbered sample items
   lineinfile:
     path: "{{ VIYA_PLAYBOOK_DIR }}/vars.yml"
     state: absent
     regexp: '\ \ #[0-9]:'
